version: '3.6'

services:
  bbb:
    image: bbb
    hostname: meet.livingutopia.org
    cap_add:
      - SYS_NICE # for realtime scheduling
      - SYS_ADMIN # for systemd
    environment:
      - container=docker
    tmpfs:
      - /run
      - /run/lock
      - /tmp:exec,mode=777
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro # for systemd
      - ./setup.sh:/opt/setup.sh
      - ./mod/freeswitch/vars.xml:/opt/freeswitch/conf/vars.xml
      - ./mod/freeswitch/external.xml:/opt/freeswitch/conf/sip_profiles/external.xml
      - ./mod/html5/systemd_start.sh:/usr/share/meteor/bundle/systemd_start.sh
      - ./mod/html5/config.yml:/usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
      - ./mod/web/override.conf:/etc/systemd/system/bbb-web.service.d/override.conf
      - ./mod/web/bigbluebutton.properties:/usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
      - ./mod/bbb-webrtc-sfu/config.yml:/usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml
    network_mode: host

  nginx:
    image: nginx:1.17
    ports:
      - "80:80"
    volumes:
      - ./mod/nginx/bbb:/etc/nginx/bbb
      - ./mod/nginx/bigbluebutton:/etc/nginx/conf.d/default.conf
    networks:
      - bluenet
    extra_hosts:
      - "host.docker.internal:10.7.7.1"

  etherpad:
    image: etherpad/etherpad:1.8.0
    environment:
      ETHERPAD_API_KEY: ${ETHERPAD_API_KEY}
    volumes:
      - ./mod/pad/settings.json:/opt/etherpad-lite/settings.json
      - ./mod/pad/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    networks:
      bluenet:
        ipv4_address: 10.7.7.4

  redis:
    image: redis:3.0-alpine
    ports:
      - "127.0.0.1:6379:6379"  # TODO: remove as soon as we updated all redis host references
    networks:
      bluenet:
        ipv4_address: 10.7.7.5 

  kurento:
    image: kurento/kurento-media-server:6.13
    # ports:
    #   # - "127.0.0.1:8889:8888"
    environment: 
      KMS_STUN_IP: 64.233.177.127 # google stun server
      KMS_STUN_PORT: 19302
      KMS_MIN_PORT: 24577
      KMS_MAX_PORT: 32768
      KMS_EXTERNAL_ADDRESS: 
      KMS_TURN_URL: 
    networks:
      bluenet:
        ipv4_address: 10.7.7.6
  
networks:
  bluenet:
    ipam:
      driver: default
      config:
        - subnet: "10.7.7.0/24"